version: "3"

services: 
    web:
        build: "./web/"
        volumes: 
            - ./web:/app

        ports: 
            - 8080:8080

    api:
        build: "./backend/"
        volumes: 
            - ./backend:/usr/src/app
        ports:
            - 5000:5000
        environment: 
            DB_PASSWORD: R00t+
        depends_on: 
            db:
                condition: service_healthy


    db:
        image: mysql
        ports:
            - 3306:3306
        volumes:
            - ./database/sqldata:/var/lib/mysql
            - ./database/setup.sql:/docker-entrypoint-initdb.d/setup.sql

        environment:
            MYSQL_ROOT_HOST: "%"
            MYSQL_ROOT_PASSWORD: R00t+
            MYSQL_USER: api
            MYSQL_PASSWORD: pass123

        healthcheck:
            test: mysqladmin ping -h 127.0.0.1 -u root --password=$$MYSQL_ROOT_PASSWORD
            timeout: 45s
            retries: 20

    reverse_proxy:
        image: nginx
        volumes: 
            - ./reverse_proxy/nginx.conf:/etc/nginx/nginx.conf
        ports:
            - 80:80


